spring:
  application:
    name: manager

  datasource:
    url: jdbc:postgresql://localhost:5433/manager_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: true



jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 3600000

admin:
  email: admin123@mail.com
  password: Admin123!

server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    csrf:
      enabled: true